apiVersion: v1
kind: Service
metadata:
  labels:
    app: pulsar
  name: pulsar
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "6650"
    port: 6650
    targetPort: 6650
  selector:
    app: manager
