
matrix:
    include:
      - language: go
        go:
          - 1.14.x
        cache:
            directories:
                - $GOPATH/pkg/mod
        env:
            global: 
                - GO111MODULE=on
        install: true
        script:
        # - cd $TRAVIS_BUILD_DIR/go/api && go build && go clean -testcache && go test ./... # Tests without cache
          - cd $TRAVIS_BUILD_DIR/go/api && go build && go test ./... # Tests with cache
          - cd $TRAVIS_BUILD_DIR/go/gen && go build
  
      - language: nodejs
        #### Config for tests with chrome, not set to lighten build   
        # dist: trusty
        # sudo: required
        # addons:
        #     chrome: stable
        language: node_js
        node_js:
            - "12.16.0"
        before_install:
            - npm install -g yarn
        install:
            - cd $TRAVIS_BUILD_DIR/webapp && yarn install --frozen-lockfile
        script:
            - cd $TRAVIS_BUILD_DIR/webapp
            - yarn run lint:full
            - yarn run build:prod
            # - yarn run test ## not set to lighten build