language: go

go:
- 1.13.x

cache:
    directories:
      - $GOPATH/pkg/mod

env:
    global: 
        - GO111MODULE=on

install: true

script:
    - cd $TRAVIS_BUILD_DIR/go/api && go build
    - cd $TRAVIS_BUILD_DIR/go/gen && go build