apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rdkapi
  name: rdkapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rdkapi
    spec:
      containers:
      - env:
        - name: GEN_HOST
          value: gen
        - name: GEN_PORT
          value: "50051"
        - name: NB_FETCH_PROFILE
          value: "10"
        - name: PORT
          value: "8082"
        - name: PULSAR_HOST
          value: 10.0.2.2
        - name: PULSAR_PORT
          value: "6650"
        - name: TOPIC
          value: randokiak-topic
        image: randokiak/randokiak-api:0.0.1
        #imagePullPolicy: Never # for use with minikube
        name: rdkapi
        ports:
        - containerPort: 8082
