apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp
spec:
  type: "NodePort"
  ports:
  - name: "4200"
    port: 4200
    targetPort: 4200
    nodePort: 30001 # fixed nodePort example
  selector:
    app: webapp
