version: '3'
services:
  pulsar:
    image: randokiak/pulsar-elastic-sink:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    volumes:
      - $PWD/data/pulsar:/pulsar/data
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"