version: '3'
services:
  webapp:
    image: randokiak/webapp:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "4200:80" #WARN : not effective in network_mode=host
    environment:
      - ELASTIC_HOST=elasticsearch
      - ELASTIC_PORT=9200
      - NGINX_LISTEN_PORT=4200
      - RDKAPI_API_HOST=rdkapi
      - RDKAPI_API_PORT=8082
    ## for local debug only
    ## extra_hosts to make things work either in host or default docker-compose
    ## port mapping is not effective => localhost:80 with this setting for webapp browse
    network_mode: host
    extra_hosts:
      - "elasticsearch:127.0.0.1"
      - "rdkapi:127.0.0.1"
  
  ### docker-compose default network mode => comment network_mode and extra_hosts
  ### if want to use container and not process running on host
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
  #   environment:
  #     - discovery.type=single-node
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #warning, will not start in docker-machine if memory is too low (less than 2gb)
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   ports:
  #     - "9200:9200"